import Head from "next/head";
import SideBar from "@/components/Sidebar";

import PlayingBar from "@/components/PlayingBar";
import Header from "@/components/Header";

import HomePage from "@/components/HomePage";
import MainLayout from "@/layouts/Mainlayout";

export default function Home() {
  return (
    <div className="flex bg-gray-900 h-screen overflow-y-scroll">
      <Head>
        <title>Music web 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-sm font-mono w-full ">
        <MainLayout>
          <HomePage></HomePage>
          <HomePage></HomePage>
          <HomePage></HomePage>
        </MainLayout>
      </main>
    </div>
  );
}
