import Head from "next/head";
import HomePage from "@/components/HomePage";
import MainLayout from "@/layouts/MainLayout";

export default function Home() {
  return (
    <div className="flex bg-zinc-900 h-screen overflow-y-scroll">
      <Head>
        <title>Music web 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-sm  w-full">
        <MainLayout>
          <HomePage></HomePage>
          <HomePage></HomePage>
          <HomePage></HomePage>
          <HomePage></HomePage>
          <HomePage></HomePage>
        </MainLayout>
      </main>
    </div>
  );
}
