import Head from "next/head";
import SideBar from "@/components/Sidebar";

import PlayingBar from "@/components/PlayingBar";
import Header from "@/components/Header";
import Container from "@/components/Container";

export default function Home() {
  return (
    <div className="bg-gray-800 h-screen overflow-hidden">
      <Head>
        <title>Music web 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-2xl font-mono">
        <div className="flex">
          <SideBar />
          <div className="flex flex-wrap w-full">
            <Header />
            <Container />
          </div>
        </div>
        <div className="flex">
          <PlayingBar />
        </div>
      </main>
    </div>
  );
}
